package com.robinzon.medicationwizard.ads.rootclasses;

public enum EAdPlacement {
    BANNER_AD_PLACEMENT_PREFIX,
    BANNER_AD_PLACEMENT_MAIN,
    BANNER_AD_PLACEMENT_SETTINGS,
    BANNER_AD_PLACEMENT_AD_MED,
    BANNER_AD_PLACEMENT_EDIT_MED,
    BANNER_AD_PLACEMENT_TEST,

    INTERSTITIAL_AD_PLACEMENT_PREFIX,
    INTERSTITIAL_AD_PLACEMENT_EDIT_MED,
    INTERSTITIAL_AD_PLACEMENT_ADD_MED,
    INTERSTITIAL_AD_PLACEMENT_SETTINGS_CHANGE,
    INTERSTITIAL_AD_PLACEMENT_TEST,

    REWARDED_VIDEO_AD_PLACEMENT_PREFIX,
    REWARDED_VIDEO_AD_PLACEMENT_MED_COLOR,
    REWARDED_VIDEO_AD_PLACEMENT_TEST,

    APP_OPEN_AD_PLACEMENT_PREFIX,
    APP_OPEN_MAIN,
    APP_OPEN_TEST
}
