// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    //Android sdk
    project.ext.set("SDK_MINIMUM_VERSION", 21)
    project.ext.set("SDK_COMPILE_VERSION", 33)
    project.ext.set("SDK_TARGET_VERSION", 33)
    project.ext.set("SDK_BUILD_TOOLS_VERSION", "33.0.2")
    //App version
    project.ext.set("VERSION_CODE", 101)
    project.ext.set("VERSION_NAME", "1.0.1")
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.2'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.6'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}